models:
  - name: members
    description: A table of all Wellthy platform accounts of type member.
    columns:
      - name: member_id
        description: Primary key for Wellthy platform profiles.
        tests:
          - not_null
  - name: created_at
    description: The timestamp for when a member profile was created.
  - name: modified_at
    description: The timestamp for when a member profile was most recently modified.
  - name: caregiving_goal
    description: The answer an onboarding member gives when prompted with "What is your caregiving goal?"
    tests:
      - accepted_values:
          values: ['Create a Care Plan'
                  ,'Create a Community Account'
                  ,'Create a Care Project'
                  ,'I'm Just Looking Around'
                  ,'Omitted: Question Disabled'
                  ,'Omitted: Project Access Only'
                  ,'Omitted: Webinar Signup'
                  ]
  - name: country
    description: The country the member resides in.
  - name: created_date
    description: '{{ doc("created_date") }}'
  - name: created_week
    description: '{{ doc("created_week") }}'
  - name: gender
    description: '{{ doc("gender") }}'
  - name: group_id
    description: '{{ doc("group_id") }}'
    tests:
      - relationships:
          to: ref('client_groups')
          field: group_id
  - name: is_deleted_member
    description: '{{ doc("is_deleted_member") }}'
  - name: is_eligibility_verified
    description: '{{ doc("is_eligibility_verified") }}'
  - name: is_proxy_account
    description: '{{ doc("is_proxy_account") }}'
    tests:
      - accepted_values:
          values: [true,false]
          quote: false
  - name: member_age_in_years
    description: The members age in years, derived from their provided birthdate.
  - name: member_id
    description: Unique identifier for a Wellthy member account.
    tests:
      - not_null
      - unique
  - name: most_recent_modified_at
    description: '{{ doc("modified_at") }}'
  - name: most_recent_modified_date
    description: '{{ doc("modified_date") }}'
  - name: preferred_contact_method
    description: '{{ doc("preferred_contact_method") }}'
    tests:
      - accepted_values:
          values: ['Email','Phone','Secondary Email']
          where: 'profile_deleted_at is null'
      - not_null:
          config:
            where: 'profile_deleted_at is null'
  - name: profile_deleted_at
    description: '{{ doc("deleted_at") }}'
  - name: profile_deleted_date
    description: '{{ doc("deleted_date") }}'
  - name: referral_source
    description: How did the member first hear about Wellthy?
  - name: member_email
    description: The email address entered upon creating a Wellthy account.
  - name: member_email_domain
    description: The domain of the email entered upon creating a Wellthy account. 
  - name: user_type
    description:
  - name: synced_at
    description: A timestamp for when the records was synced via Fivetran.
